name: Security Audit
permissions:
  contents: read

on:
  schedule:
    - cron: '0 0 * * *'
  pull_request:
    paths:
      - '**/Cargo.toml'
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: dtolnay/rust-toolchain@stable

      - name: Install cargo-audit
        run: cargo install cargo-audit

      - uses: actions/checkout@v4

      - name: Cache Rust toolchain and build artifacts
        uses: Swatinem/rust-cache@v2
        with:
          # The cache should not be shared between different workflows and jobs.
          shared-key: ${{ github.workflow }}-${{ github.job }}

      - name: Run security audit
        run: cargo audit --deny unsound --deny yanked
